name: intercepted_http
description: Wrapper around http to provide simple interceptors
version: 0.0.1
author: MasseElch

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'

dependencies:
  http: ^0.13.0
